name: trello_challenge
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state management
  get: 4.6.1

  # network
  dio: 4.0.4

  # local storage
  shared_preferences: 2.0.13

  #localization facilities
  intl: 0.17.0

  # UI
  cupertino_icons: 1.0.2
  flutter_neumorphic: 3.2.0
  gap: 2.0.0
  google_fonts: 2.3.1
  flutter_svg: 1.0.3
  bot_toast: 4.0.1
  lottie: 1.2.2
  persistent_bottom_nav_bar_v2: 4.1.8
  flutter_keyboard_visibility: 5.2.0
  cached_network_image: 3.2.0
  image_picker: 0.8.4+11
  extended_image: 6.0.2+1

  #socket io
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

  #gen uuid
  uuid: ^3.0.6

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lotties/

